import "./globals.css";

import { Providers } from "@/Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Ubuntu } from 'next/font/google'

const ubuntu = Ubuntu({
  weight: ['300', '400'],
  subsets: ['latin'],
})

export default function RootLayout({ children }) {


  return (
    <html lang="en" className="w-full h-full">
      <body className={`{${ubuntu.className} w-full h-full}`}
      >
        <Providers>
          {children}
        </Providers>
          
      </body>
    </html>
  );
}
